name: 02 events manual

on:
  workflow_dispatch:
    inputs:
      string_input:
        description: 'Írj valamit'
        type: string
        required: false
      boolean_input:
        description: 'Igaz vagy hamis?'
        type: boolean
        required: false
      choice_input:
        description: 'Válassz egy opciót'
        type: choice
        options:
          - igen
          - nem
        required: true
      number_input:
        description: 'Adj meg egy számot'
        type: number
        required: false
      environment_input:
        description: 'Válassz egy környezetet'
        type: environment
        required: false

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print string input
        run: |
          echo "String input: ${{ github.event.inputs.string_input }}"

      - name: Print boolean input
        run: |
          echo "Boolean input: ${{ github.event.inputs.boolean_input }}"

      - name: Print choice input
        run: |
          echo "Choice input: ${{ github.event.inputs.choice_input }}"

      - name: Print number input
        run: |
          echo "Number input: ${{ github.event.inputs.number_input }}"

      - name: Print environment input
        run: |
          echo "Environment input: ${{ github.event.inputs.environment_input }}"
