name: 02 events manual choose

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'VÃ¡lassz'
        type: choice
        options:
          - igen
          - nem


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello from GitHub Actions!"
