name: 03 checkout action 01

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code all files
        uses: actions/checkout@v4

      - name: Pretty print folder structure
        run: tree -a -I ".git"

      - name: Checkout only TS files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/**/*.ts
          sparse-checkout-cone-mode: false

      - name: Pretty print folder structure
        run: tree -a -I ".git"

      - name: Checkout fodlers
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            assets

      - name: Pretty print folder structure
        run: tree -a -I ".git"

