name: 04 setup node cache action 02

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Activete PNPM
        run: | 
         corepack enable
         pnpm -v  

#       CACHE START
      - name: Get pnpm store directory
        id: pnpm-store-path
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Restore pnpm-store from cache
        id: pnpm-store-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-store-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Save pnpm-store to cache
        if: steps.pnpm-store-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
#       CACHE END

      - name: Use consola package
        run: node src/hello.js


