name: 06 secrets 01

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Use an API key
        run: echo "Key is set"
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Set API key
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV # export to global github env -> $API_KEY

      - name: Use API key in next step
        run: |
          echo "Using API key..."
          curl -H "Authorization: Bearer $API_KEY" https://api.example.com



