name: Show GitHub Context

on:
  workflow_dispatch:

jobs:
  show-context:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Basic Repo Info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Actor: ${{ github.actor }}"

      - name: Print Branch and Commit Info
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"

      - name: Print Event Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Event Path: ${{ github.event_path }}"

      - name: Print Trigger Info (head/base for PR)
        run: |
          echo "Head Ref: ${{ github.head_ref }}"
          echo "Base Ref: ${{ github.base_ref }}"

      - name: Print Event Payload Field (example PR title)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "PR title: ${{ github.event.pull_request.title }}"

      - name: Print Token and Permissions Info
        run: |
          echo "Token exists?: ${{ github.token != '' }}"
          echo "Permissions: ${{ toJson(github.permissions) }}"
