name: 09 deploy 01

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://github.com/test
    steps:
      - name: Print message
        run: echo "Hello from GitHub Actions!"

  prod:
    needs:
      - test
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://github.com/prod
    steps:
      - name: Print message
        run: echo "Hello from GitHub Actions!"


